server:
  port: 7007
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:7000/eureka/
  instance:
    hostname: localhost
zuul:
  routes:
    e-p:
      path: /e-p/**
      serviceId: eureka-provider
    e-c:
      path: /e-c/**
      serviceId: eureka-consumer
yxwfilter:
  ip:
    whitelist: 127.0.0.1,172.20.10.2,172.20.10.1
    whitelistenabled: true

